version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  beanstalk:
    image: 'schickling/beanstalkd'
    ports:
      - '11300:11300'
